# Generated by Django 2.2.1 on 2019-05-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20190513_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='daysSince',
            field=models.IntegerField(default=0),
        ),
    ]
