# Generated by Django 2.2.1 on 2019-05-14 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20190514_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='daysSince',
        ),
        migrations.CreateModel(
            name='date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.DateField(auto_now_add=True)),
                ('completed', models.IntegerField(default=0)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date', to='tasks.Task')),
            ],
        ),
    ]
